/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recipe/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tworzy nowy przepis
         * @description Tworzy nowy przepis z podanymi danymi i opcjonalnym obrazem
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @description Dane przepisu w formacie JSON */
                        recipeData?: string;
                        /**
                         * Format: binary
                         * @description Zdjęcie przepisu
                         */
                        image?: string;
                    };
                };
            };
            responses: {
                /** @description Przepis utworzony */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: string;
                            recipe?: components["schemas"]["Recipe"];
                        };
                    };
                };
                /** @description Błędne dane wejściowe */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Brak autoryzacji */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Błąd serwera */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipe/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pobiera szczegóły przepisu po ID
         * @description Zwraca szczegóły przepisu. Jeśli użytkownik jest autorem, kupił przepis lub przepis jest darmowy, zwracane są pełne szczegóły.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID przepisu */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Szczegóły przepisu */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recipe"];
                    };
                };
                /** @description Nieprawidłowe ID przepisu */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Brak autoryzacji */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Przepis nie znaleziony */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Błąd serwera */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RecipeStep: {
            /** @description Tytuł kroku */
            title: string;
            /**
             * @description Typ kroku
             * @enum {string}
             */
            stepType: "ADD_INGREDIENT" | "COOKING" | "DESCRIPTION";
            /** @description ID składnika (tylko dla ADD_INGREDIENT) */
            ingredientId?: number;
            /** @description Ilość składnika (tylko dla ADD_INGREDIENT) */
            amount?: number;
            /** @description Czas trwania (tylko dla COOKING) */
            time?: string;
            /** @description Temperatura (tylko dla COOKING) */
            temperature?: number;
            /** @description Prędkość mieszania (tylko dla COOKING) */
            mixSpeed?: number;
            /** @description Opis (tylko dla DESCRIPTION) */
            description?: string;
        };
        NewRecipe: {
            /** @description Tytuł przepisu */
            title: string;
            /** @description Opis przepisu */
            description: string;
            /** @description Kategoria przepisu */
            category: string;
            /** @description Cena przepisu */
            price: number;
            /** @description Kroki przepisu */
            steps: components["schemas"]["RecipeStep"][];
        };
        Recipe: components["schemas"]["NewRecipe"] & {
            /** @description ID przepisu */
            id?: number;
            /**
             * Format: date-time
             * @description Data utworzenia
             */
            createdAt?: string;
            author?: {
                id?: number;
                name?: string;
                surname?: string;
            };
            /** @description URL obrazu przepisu */
            image?: string;
            /** @description Czy użytkownik ma dostęp do pełnych szczegółów przepisu */
            permission?: boolean;
        };
        NewRecipeInfo: {
            title?: string;
            description?: string;
            category?: string;
            price?: number;
            steps?: components["schemas"]["RecipeStep"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
